exclude: .*\.tsv|\.clang-format|dcist_launch_system/config/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [--select, I, --fix]
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
