"""fleet-adt4: Interactive fleet management TUI and CLI for the ADT4 multi-robot system."""

import json
import os
import pathlib
import shlex
import sys

def _maybe_reexec():
    """Re-exec with spark_env Python if ADT4_ENV points to one."""
    # Uses ADT4_ENV env var (set in ~/.zshrc on each machine).
    if not os.environ.get("_FLEET_ADT4_REEXEC"):
        _adt4_env = os.environ.get("ADT4_ENV", "")
        if _adt4_env:
            _spark_env = pathlib.Path(_adt4_env) / "spark_env"
            _spark_python = _spark_env / "bin" / "python3"
            if _spark_python.exists() and sys.prefix != str(_spark_env):
                os.environ["_FLEET_ADT4_REEXEC"] = "1"
                os.execv(str(_spark_python), [str(_spark_python)] + sys.argv)


import shutil
import subprocess
import threading

import click
import yaml
from rich.console import Console
from rich.table import Table


from dcist_launch_system.fleet_helpers import (
    _DEFAULT_TOPOLOGY,
    _STATUS_COLORS,
    _STATUS_NAMES,
    _STATUS_NOMINAL,
    _quote_path,
    check_machine,
    check_zenoh_config,
    check_zenoh_port,
    check_silvus_route,
    compute_robot_readiness,
    deploy_zenoh_config,
    generate_namespaced_rviz,
    detect_network,
    filter_reachable,
    generate_zenoh_endpoints,
    get_remote_status,
    get_ros_node_status,
    get_silvus_link_quality,
    get_silvus_radio_details,
    NodeStatusPoller,
    hash_remote_experiment,
    patch_zenoh_config_local,
    list_remote_experiments,
    load_topology,
    ping_host,
    resolve_machines,
    rsync_transfer,
    run_parallel,
    send_tmux_keys,
    ssh_cmd,
    get_local_ip_for_network,
    check_iperf3,
    run_iperf3_test,
)

console = Console()

_TMUX_DIR = pathlib.Path(__file__).resolve().parent.parent.parent.parent / "tmux" / "autogenerated"

# ---------------------------------------------------------------------------
# CLI mode (click subcommands)
# ---------------------------------------------------------------------------


class FleetContext:
    def __init__(self, network, topology_path, output_root):
        self.topology = load_topology(topology_path)
        self.output_root = output_root
        self.network = network or detect_network(self.topology)
        if not self.network:
            click.secho(
                "Could not auto-detect network. Use --network to specify.", fg="red"
            )
            sys.exit(1)

    def machines(self, roles=None, names=None):
        return resolve_machines(self.topology, self.network, roles=roles, names=names)


@click.group(invoke_without_command=True)
@click.option(
    "--network",
    "-n",
    type=click.Choice(["mit_wifi", "penn_wifi", "silvus"]),
    default=None,
    help="Network to use (auto-detected if omitted)",
)
@click.option("--topology", "-t", type=click.Path(exists=True), default=None)
@click.option("--output-root", "-o", default="~/adt4_output", help="Remote output root")
@click.pass_context
def cli(ctx, network, topology, output_root):
    """ADT4 Fleet Management Tool. Run without subcommand for interactive TUI."""
    ctx.ensure_object(dict)
    ctx.obj["network"] = network
    ctx.obj["topology"] = topology
    ctx.obj["output_root"] = output_root
    if ctx.invoked_subcommand is None:
        _launch_tui(network, topology, output_root)


# --- status ---


@cli.command()
@click.option("--role", type=click.Choice(["robot", "base_station"]), default=None)
@click.pass_context
def status(ctx, role):
    """Check connectivity to all fleet machines (ping + SSH)."""
    fc = FleetContext(
        ctx.obj["network"], ctx.obj["topology"], ctx.obj["output_root"]
    )
    roles = [role] if role else None
    machines = fc.machines(roles=roles)
    if not machines:
        click.secho("No machines found on this network.", fg="yellow")
        return

    click.secho(f"Network: {fc.network}  ({len(machines)} machines)\nChecking connectivity...", fg="cyan")
    reachable, unreachable = filter_reachable(machines)

    all_checked = reachable + unreachable
    all_checked.sort(key=lambda m: m["name"])

    table = Table(title="Fleet Status")
    table.add_column("Machine", style="bold")
    table.add_column("Role")
    table.add_column("Platform")
    table.add_column("IP")
    table.add_column("Ping")
    table.add_column("SSH")
    table.add_column("Status")

    for m in all_checked:
        ping_str = "[green]OK[/]" if m.get("ping") else "[red]FAIL[/]"
        ssh_str = "[green]OK[/]" if m.get("ssh") else "[red]FAIL[/]"
        if m.get("online"):
            status_str = "[bold green]ONLINE[/]"
        elif m.get("ping"):
            status_str = "[yellow]NO SSH[/]"
        else:
            status_str = "[red]OFFLINE[/]"
        table.add_row(
            m["name"], m["role"], m["platform_id"] or "---",
            m["ip"], ping_str, ssh_str, status_str,
        )

    console.print(table)
    n_online = len(reachable)
    n_total = len(all_checked)
    console.print(f"\n[bold]{n_online}/{n_total} machines online[/]")


# --- maps ---


@cli.command()
@click.option("--machine", "-m", multiple=True, help="Filter to specific machines")
@click.option("--detail", is_flag=True, help="Show subdirs and sizes")
@click.pass_context
def maps(ctx, machine, detail):
    """List experiments on fleet machines."""
    fc = FleetContext(
        ctx.obj["network"], ctx.obj["topology"], ctx.obj["output_root"]
    )
    names = list(machine) if machine else None
    machines = fc.machines(names=names)

    def fetch(m):
        return list_remote_experiments(m["user"], m["ip"], fc.output_root)

    results = run_parallel(fetch, machines)

    table = Table(title="Experiments")
    table.add_column("Machine", style="bold")
    table.add_column("Experiment")
    if detail:
        table.add_column("Subdirs")
        table.add_column("Size")

    for m, exps in sorted(results, key=lambda x: x[0]["name"]):
        if isinstance(exps, Exception):
            row = [m["name"], f"[red]Error: {exps}[/]"]
            if detail:
                row += ["", ""]
            table.add_row(*row)
            continue
        if not exps:
            row = [m["name"], "[dim]no experiments[/]"]
            if detail:
                row += ["", ""]
            table.add_row(*row)
            continue
        for i, exp in enumerate(sorted(exps, key=lambda e: e["name"])):
            mname = m["name"] if i == 0 else ""
            row = [mname, exp["name"]]
            if detail:
                row += [", ".join(exp["subdirs"]), exp["size"]]
            table.add_row(*row)

    console.print(table)


# --- transfer ---


@cli.command()
@click.option("--from", "src_machine", required=True, help="Source machine name")
@click.option("--experiment", "-e", required=True, help="Experiment directory name")
@click.option("--as", "dest_name", default=None, help="Rename experiment on destination")
@click.option("--to", "dst_machines", multiple=True, help="Dest machines (default: all other robots)")
@click.option("--subdir", default=None, help="Only transfer a specific subdir (e.g. hydra, roman)")
@click.option("--include-bags", is_flag=True, help="Include recorded_data/ (rosbags). Excluded by default.")
@click.option("--delete", is_flag=True, help="Delete extraneous files on destination")
@click.option("--relay", is_flag=True, help="Force relay through operator machine")
@click.pass_context
def transfer(ctx, src_machine, experiment, dest_name, dst_machines, subdir, include_bags, delete, relay):
    """Transfer an experiment from one machine to others. Excludes rosbags by default."""
    fc = FleetContext(
        ctx.obj["network"], ctx.obj["topology"], ctx.obj["output_root"]
    )
    all_machines = fc.machines()
    src = next((m for m in all_machines if m["name"] == src_machine), None)
    if not src:
        click.secho(f"Source machine '{src_machine}' not found on network.", fg="red")
        return

    src_status = check_machine(src)
    if not src_status["online"]:
        click.secho(f"Source machine '{src_machine}' ({src['ip']}) is not reachable (ping={src_status['ping']}, ssh={src_status['ssh']}).", fg="red")
        return

    if dst_machines:
        dests = [m for m in all_machines if m["name"] in dst_machines]
    else:
        dests = [m for m in all_machines if m["name"] != src_machine]

    if not dests:
        click.secho("No destination machines found.", fg="yellow")
        return

    click.echo("Checking destination reachability (ping + SSH)...")
    reachable, unreachable = filter_reachable(dests)
    for dst in unreachable:
        reason = "offline" if not dst.get("ping") else "no SSH"
        click.secho(f"  Skipping {dst['name']} ({dst['ip']}) — {reason}", fg="yellow")
    if not reachable:
        click.secho("No reachable destinations.", fg="red")
        return

    dest_name = dest_name if dest_name is not None else f"prior_{experiment}"
    path_suffix = f"/{subdir}" if subdir else ""
    src_path = f"{fc.output_root}/{experiment}{path_suffix}"

    label = f"{src_machine}:{src_path}"
    if dest_name != experiment:
        label += f" (as {dest_name})"
    exclude = [] if include_bags else ["recorded_data/"]
    if not include_bags:
        click.secho("Excluding rosbags (recorded_data/). Use --include-bags to include.", fg="yellow")
    click.secho(f"Transferring {label} -> {len(reachable)} machines", fg="cyan")
    for dst in reachable:
        dst_path = f"{fc.output_root}/{dest_name}{path_suffix}"
        click.echo(f"  -> {dst['name']} ({dst['ip']})...")
        ok, method, msg = rsync_transfer(
            src["user"], src["ip"], src_path,
            dst["user"], dst["ip"], dst_path,
            delete=delete, relay=relay, stream=True, exclude=exclude,
        )
        if ok:
            click.secho(f"  {dst['name']}: OK ({method})", fg="green")
        else:
            click.secho(f"  {dst['name']}: FAIL ({method}): {msg}", fg="red")


# --- verify ---


@cli.command()
@click.option("--experiment", "-e", required=True, help="Experiment to verify")
@click.option("--machine", "-m", multiple=True, help="Filter to specific machines")
@click.pass_context
def verify(ctx, experiment, machine):
    """Verify map consistency across machines."""
    fc = FleetContext(
        ctx.obj["network"], ctx.obj["topology"], ctx.obj["output_root"]
    )
    names = list(machine) if machine else None
    machines = fc.machines(names=names)

    def fetch_hashes(m):
        return hash_remote_experiment(m["user"], m["ip"], fc.output_root, experiment)

    results = run_parallel(fetch_hashes, machines)
    machine_hashes = {m["name"]: h for m, h in results if isinstance(h, dict)}

    if not machine_hashes:
        click.secho("No machines returned hash data.", fg="yellow")
        return

    # Collect all files across all machines
    all_files = sorted(set(f for h in machine_hashes.values() for f in h))
    machine_names = sorted(machine_hashes.keys())

    table = Table(title=f"Map Verification: {experiment}")
    table.add_column("File", style="bold")
    for mname in machine_names:
        table.add_column(mname)

    diffs = 0
    for fpath in all_files:
        hashes_for_file = {mn: machine_hashes[mn].get(fpath) for mn in machine_names}
        unique_hashes = set(v for v in hashes_for_file.values() if v)
        is_consistent = len(unique_hashes) <= 1

        row = [fpath]
        for mn in machine_names:
            h = hashes_for_file[mn]
            if h is None:
                row.append("[dim]missing[/]")
                if unique_hashes:
                    is_consistent = False
            elif is_consistent:
                row.append("[green]OK[/]")
            else:
                row.append(f"[red]{h[:8]}[/]")
        if not is_consistent:
            diffs += 1
        table.add_row(*row)

    console.print(table)
    if diffs == 0:
        console.print("[bold green]All files consistent across machines.[/]")
    else:
        console.print(f"[bold red]{diffs} file(s) differ across machines.[/]")


# --- launch ---


@cli.command()
@click.option("--machine", "-m", multiple=True, help="Machines to launch on")
@click.option("--session", "-s", required=True, help="Tmux session name")
@click.option("--experiment", "-e", required=True, help="Experiment name (for output dir)")
@click.option("--prior-map", "-p", default=None, help="Prior map path on remote machines")
@click.option("--base-station", is_flag=True, help="Also launch base station on willow")
@click.option("--force", "-f", is_flag=True, help="Overwrite existing output directories")
@click.option("--yes", "-y", is_flag=True, help="Skip confirmation")
@click.option("--dry-run", "-d", is_flag=True, help="Show commands without executing")
@click.pass_context
def launch(ctx, machine, session, experiment, prior_map, base_station, force, yes, dry_run):
    """Launch run-adt4 remotely on fleet robots."""
    fc = FleetContext(
        ctx.obj["network"], ctx.obj["topology"], ctx.obj["output_root"]
    )
    names = list(machine) if machine else None
    robots = fc.machines(roles=["robot"], names=names)

    targets = []
    for m in robots:
        sess = session
        targets.append((m, sess))

    if base_station:
        bs_machines = fc.machines(roles=["base_station"])
        for m in bs_machines:
            targets.append((m, "base_station"))

    if not targets:
        click.secho("No target machines found.", fg="yellow")
        return

    table = Table(title="Launch Plan")
    table.add_column("Machine", style="bold")
    table.add_column("Session")
    table.add_column("Platform")
    table.add_column("Output Dir")
    table.add_column("Prior Map")

    cmds = []
    force_flag = " -f" if force else ""
    for m, sess in targets:
        output_dir = f"{fc.output_root}/{experiment}"
        prior_flag = f" -p {_quote_path(prior_map)}" if prior_map else ""
        remote_cmd = (
            f"cd ~/dcist_ws && source install/setup.zsh && "
            f"src/awesome_dcist_t4/dcist_launch_system/bin/run-adt4 "
            f"{shlex.quote(sess)} -n {shlex.quote(m['name'])} "
            f"-c {shlex.quote(m['platform_id'])} "
            f"-o {_quote_path(output_dir)} -y{force_flag}{prior_flag} "
            f"--tmuxp-args \"-d\""
        )
        table.add_row(
            m["name"], sess, m["platform_id"] or "---",
            output_dir, prior_map or "---",
        )
        cmds.append((m, remote_cmd, sess))

    console.print(table)

    if dry_run:
        click.secho("\nDry run — commands that would be executed:", fg="cyan")
        for m, cmd, _ in cmds:
            click.echo(f"  ssh {m['user']}@{m['ip']} \"{cmd}\"")
        return

    # Pre-launch check for existing sessions
    click.echo("Checking for running sessions...")
    def check_session(item):
        m, _, sess = item
        rc, _, _ = ssh_cmd(m["user"], m["ip"], f"tmux has-session -t {shlex.quote(sess)} 2>/dev/null", timeout=5)
        return m['name'], rc == 0, sess

    session_checks = run_parallel(check_session, cmds)
    conflicts = [r for _, r in session_checks if r[1]]
    if conflicts:
        for mname, _, sess in conflicts:
            click.secho(f"  Warning: Session '{sess}' is already running on {mname}.", fg="yellow")
        if click.confirm("Terminate existing sessions and proceed?"):
            for mname, _, sess in conflicts:
                # Find the machine dict
                m = next(m for m, _, _ in cmds if m["name"] == mname)
                click.echo(f"  Terminating session on {mname}...")
                ssh_cmd(m["user"], m["ip"], f"tmux kill-session -t {shlex.quote(sess)}", timeout=5)
        else:
            click.secho("Aborted by user.", fg="red")
            return

    if not yes:
        click.confirm("Proceed with launch?", abort=True)

    def do_launch(item):
        m, cmd, _ = item
        rc, out, err = ssh_cmd(m["user"], m["ip"], cmd, timeout=30)
        return rc, out, err

    results = run_parallel(do_launch, cmds)
    for (m, _), (rc_or_exc) in results:
        if isinstance(rc_or_exc, Exception):
            click.secho(f"  {m['name']}: ERROR - {rc_or_exc}", fg="red")
        else:
            rc, out, err = rc_or_exc
            if rc == 0:
                click.secho(f"  {m['name']}: launched", fg="green")
            else:
                click.secho(f"  {m['name']}: FAILED (rc={rc}) {err}", fg="red")


# --- monitor ---


@cli.command()
@click.option("--machine", "-m", multiple=True, help="Filter to specific machines")
@click.option("--watch", "-w", is_flag=True, help="Auto-refresh every 10s")
@click.pass_context
def monitor(ctx, machine, watch):
    """Monitor fleet status (tmux sessions, ROS2 procs, load, disk)."""
    fc = FleetContext(
        ctx.obj["network"], ctx.obj["topology"], ctx.obj["output_root"]
    )
    names = list(machine) if machine else None
    machines = fc.machines(names=names)

    def _print_status():
        def fetch(m):
            return get_remote_status(m["user"], m["ip"])

        results = run_parallel(fetch, machines)

        table = Table(title="Fleet Monitor")
        table.add_column("Machine", style="bold")
        table.add_column("Tmux Sessions")
        table.add_column("ROS2 Procs")
        table.add_column("Load")
        table.add_column("Disk Free")

        for m, st in sorted(results, key=lambda x: x[0]["name"]):
            if isinstance(st, Exception):
                table.add_row(m["name"], f"[red]{st}[/]", "", "", "")
                continue
            table.add_row(
                m["name"],
                st["tmux_sessions"],
                st["ros2_procs"],
                st["load"],
                st["disk"],
            )
        console.print(table)

    if not watch:
        _print_status()
        return

    import time

    try:
        while True:
            console.clear()
            _print_status()
            console.print("[dim]Refreshing in 10s... (Ctrl+C to stop)[/]")
            time.sleep(10)
    except KeyboardInterrupt:
        pass


@cli.command()
@click.option("--machine", "-m", multiple=True, help="Filter to specific machines")
@click.option("--dry-run", is_flag=True, help="Preview configs without deploying")
@click.pass_context
def zenoh(ctx, machine, dry_run):
    """Generate and deploy Zenoh router configs based on topology.

    Base stations get connect endpoints to robots (star topology).
    Robots listen only — no outbound connections.
    """
    fc = FleetContext(
        ctx.obj["network"], ctx.obj["topology"], ctx.obj["output_root"]
    )
    names = list(machine) if machine else None
    machines = fc.machines(names=names)

    table = Table(title=f"Zenoh Configs — network: {fc.network}")
    table.add_column("Machine", style="bold")
    table.add_column("Role")
    table.add_column("Connect Endpoints")
    table.add_column("Status")

    for m in sorted(machines, key=lambda x: x["name"]):
        mname = m["name"]
        try:
            endpoints = generate_zenoh_endpoints(fc.topology, fc.network, mname)
        except KeyError:
            table.add_row(mname, m["role"], "?", "[red]No address[/]")
            continue

        n = len(endpoints)
        connect_str = f"{n} robot(s)" if n else "[dim]none (listen only)[/]"

        if dry_run:
            table.add_row(mname, m["role"], connect_str, "[yellow]dry-run[/]")
            for ep in endpoints:
                console.print(f"  [dim]{mname} → {ep}[/]")
        else:
            ok, msg = deploy_zenoh_config(m["user"], m["ip"], endpoints)
            status = f"[green]{msg}[/]" if ok else f"[red]{msg}[/]"
            table.add_row(mname, m["role"], connect_str, status)

    console.print(table)
    if dry_run:
        console.print("[yellow]Dry run — no configs deployed. Remove --dry-run to deploy.[/]")


# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# TUI mode (textual) — delegated to dcist_launch_system.tui.app
# ---------------------------------------------------------------------------

from dcist_launch_system.tui.app import _launch_tui  # noqa: F401


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    cli()
