/**:
  ros__parameters:
    map_frame_id: vision
    odom_frame_id: body
    robot_id: 0
    visualize: true
    viz_min_viz_dt: 0.25
    viz_rotate_img: "CW"
    output_roman_map: ~/roman_map.pkl
    # default T_camera_flu assumes camera frame is right-down-forward (rdf)
    T_camera_flu: [
      0., 0., 1., 0.,
      0., -1., 0., 0.,
      1., 0., 0., 0.,
      0., 0., 0., 1.]