---
/**:
  ros__parameters:
    heracles_ip: $(env ADT4_HERACLES_IP)
    heracles_port: $(env ADT4_HERACLES_PORT)
    heracles_neo4j_user: $(env ADT4_NEO4J_USERNAME)
    heracles_neo4j_pass: $(env ADT4_NEO4J_PASSWORD)
    # Resolved relative to heracles.resources (or put an absolute path)
    object_labelspace: ade20k_mit_label_space.yaml
    region_labelspace: b45_label_space.yaml
