---
graph: {type: GraphFromRos}
renderer:
  graph:
    collapse_layers: true
  layers:
    2:
      z_offset_scale: 2.0
      visualize: false
      nodes:
        scale: 0.40
        color: {type: LabelColorAdapter, alpha: 0.8, use_sphere: false}
      text:
        draw: true
        collapse: true
        adapter: {type: LabelIdTextAdapter}
        height: 0.5
        scale: 0.45
      bounding_boxes: {draw: true, collapse: true, scale: 0.05, edge_scale: 0.05, alpha: 0.9, edge_break_ratio: 0.5}
      edges: {interlayer_use_source: true, interlayer_scale: 0.08, interlayer_alpha: 0.9, interlayer_use_color: true}
  partitions:
    2:
      z_offset_scale: 0.0
      visualize: true
      nodes:
        scale: 0.15
        alpha: 0.9
        use_sphere: false
        color: {type: PartitionColorAdapter}
      edges: {scale: 0.05, alpha: 0.9, draw_interlayer: false}
      text: {draw_layer: true, height: 0.9, scale: 0.8}
    3:
      visualize: false
      z_offset_scale: 3.0
      nodes:
        scale: 0.2
        color: {type: LabelColorAdapter}
        alpha: 0.9
        use_sphere: true
      boundaries: {draw: false}
      edges: {scale: 0.04, alpha: 0.5, use_color: false, interlayer_use_source: false, interlayer_scale: 0.04, interlayer_alpha: 0.4}
