/**:
  ros__parameters:
    submap_num_segments: 40
    submap_overlapping_segments: 20
    lc_required_associations: 8
    ego_id: 1
    ego_name: spot
    ego_flu_ref_frame: spot/body
    ego_odom_frame: spot/vision
    team_ids: [0]
    team_names: ['']
    team_flu_ref_frames: ['']
    team_odom_frames: ['']
    prior_session_maps: [$(env ADT4_PRIOR_ROMAN_PATH)]
    prior_session_ids: [0]
