---
/**:
  ros__parameters:
    use_sim_time: false
    simulation:
      sim_enabled: false
      sim_address: 127.0.0.1
      sim_port: 30000
    svo:
      use_svo_timestamps: true
      publish_svo_clock: false
      svo_loop: false
      svo_realtime: false
      play_from_frame: 0
      replay_rate: 1.0
    general:
      camera_timeout_sec: 5
      camera_max_reconnect: 5
      camera_flip: false
      self_calib: true
      serial_number: 0
      pub_resolution: CUSTOM
      pub_downscale_factor: 2.0
      pub_frame_rate: 15.0
      enable_image_validity_check: 1
      gpu_id: -1
      optional_opencv_calibration_file: ''
      async_image_retrieval: false
    video:
      saturation: 4
      sharpness: 4
      gamma: 8
      auto_exposure_gain: true
      exposure: 80
      gain: 80
      auto_whitebalance: true
      whitebalance_temperature: 42
    sensors:
      publish_imu_tf: false
      sensors_image_sync: false
      sensors_pub_rate: 100.
    region_of_interest:
      automatic_roi: false
      depth_far_threshold_meters: 2.5
      image_height_ratio_cutoff: 0.5
      apply_to_depth: true
      apply_to_positional_tracking: true
      apply_to_object_detection: true
      apply_to_body_tracking: true
      apply_to_spatial_mapping: true
    depth:
      depth_mode: NEURAL_PLUS
      depth_stabilization: 30
      openni_depth_mode: false
      point_cloud_freq: 10.0
      point_cloud_res: COMPACT
      depth_confidence: 95
      depth_texture_conf: 100
      remove_saturated_areas: true
    pos_tracking:
      pos_tracking_enabled: true
      pos_tracking_mode: GEN_1
      imu_fusion: true
      publish_tf: true
      publish_map_tf: true
      map_frame: map
      odometry_frame: odom
      area_memory_db_path: ''
      area_memory: true
      reset_odom_with_loop_closure: true
      depth_min_range: 0.0
      set_as_static: false
      set_gravity_as_origin: true
      floor_alignment: false
      initial_base_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      path_pub_rate: 2.0
      path_max_count: -1
      two_d_mode: false
      fixed_z_value: 0.0
      transform_time_offset: 0.0
      reset_pose_with_svo_loop: true
    gnss_fusion:
      gnss_fusion_enabled: false
      gnss_fix_topic: /fix
      gnss_zero_altitude: false
      h_covariance_mul: 1.0
      v_covariance_mul: 1.0
      publish_utm_tf: true
      broadcast_utm_transform_as_parent_frame: false
      enable_reinitialization: false
      enable_rolling_calibration: true
      enable_translation_uncertainty_target: false
      gnss_vio_reinit_threshold: 5.0
      target_translation_uncertainty: 0.1
      target_yaw_uncertainty: 0.1
    mapping:
      mapping_enabled: false
      resolution: 0.05
      max_mapping_range: 5.0
      fused_pointcloud_freq: 1.0
      clicked_point_topic: /clicked_point
      pd_max_distance_threshold: 0.15
      pd_normal_similarity_threshold: 15.0
    object_detection:
      od_enabled: false
      enable_tracking: true
      detection_model: MULTI_CLASS_BOX_FAST
      max_range: 20.0
      filtering_mode: NMS3D
      prediction_timeout: 2.0
      allow_reduced_precision_inference: false
    body_tracking:
      bt_enabled: false
      model: HUMAN_BODY_MEDIUM
      body_format: BODY_38
      allow_reduced_precision_inference: false
      max_range: 15.0
      body_kp_selection: FULL
      enable_body_fitting: false
      enable_tracking: true
      prediction_timeout_s: 0.5
      confidence_threshold: 50.0
      minimum_keypoints_threshold: 5
    stream_server:
      stream_enabled: false
      codec: H264
      port: 30000
      bitrate: 12500
      gop_size: -1
      adaptative_bitrate: false
      chunk_size: 16084
      target_framerate: 0
    advanced:
      thread_sched_policy: SCHED_BATCH
      thread_grab_priority: 50
      thread_sensor_priority: 70
      thread_pointcloud_priority: 60
    debug:
      sdk_verbose: 1
      sdk_verbose_log_file: ''
      debug_common: false
      debug_sim: false
      debug_video_depth: false
      debug_camera_controls: false
      debug_point_cloud: false
      debug_positional_tracking: false
      debug_gnss: false
      debug_sensors: false
      debug_mapping: false
      debug_terrain_mapping: false
      debug_object_detection: false
      debug_body_tracking: false
      debug_roi: false
      debug_streaming: false
      debug_advanced: false
