services:
  # Development Environment
  dev:
    build:
      context: .
      target: base
      args:
        - MAKE_JOBS=${DOCKER_MAKE_JOBS:-4}
    container_name: dcist_dev
    volumes:
      - ./adt4_src:/dcist_ws/src
      - ./data:/data:rw
      - ./adt4_output:/root/adt4_output:rw
      # For GUI forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    stdin_open: true
    tty: true

  # Deployment Environment
  deploy:
    build:
      context: .
      target: deployment
      args:
        - MAKE_JOBS=${DOCKER_MAKE_JOBS:-4}
    container_name: dcist_deploy
    volumes:
      - ./data:/data:rw
      - ./adt4_output:/root/adt4_output:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    stdin_open: true
    tty: true