/**:
  ros__parameters:
    submap_num_segments: 40
    submap_overlapping_segments: 20
    lc_required_associations: 5
    ego_id: 1
    ego_name: $(var robot_name)
    ego_flu_ref_frame: $(var robot_name)/base_link
    ego_odom_frame: $(var robot_name)/odom
    team_ids: [0]
    team_names: [""]
    team_flu_ref_frames: [""]
    team_odom_frames: [""]
    prior_session_maps: [""]
    prior_session_ids: [0]
    output_dir: $(var output_dir)/roman
