/**:
  ros__parameters:
    cameras: [frontleft, frontright, hand]
    robot:
      setup_logging: false
      should_retry: true
      ip: $(env ADT4_BOSDYN_IP)
      username: $(env ADT4_BOSDYN_USERNAME)
      password: $(env ADT4_BOSDYN_PASSWORD)
    camera_poll_period_s: 0.5
    hand.color_suffix: color_image
    hand.depth_suffix: depth
