model_name: gpt-4o
prompt_mode: default
prompt: $ADT4_NLU_INTERFACE_PKG/resources/prompts/prompt_pddl_planner.yaml
prompt: prompt_pddl_planner
num_incontext_examples: -1
temperature: 0.0
seed: 100
api_timeout: 120.0
debug: True
