planners:
    goto_points:
        plugin:
            type: GotoPoints

    language_planner:
        plugin:
            type: LanguagePlanner
            domain_type: pddl
            pddl_domain_name: GotoObjectDomain
            llm_config: ${ADT4_NLU_INTERFACE_PKG}/config/llm_config.yaml

    tsp_planner:
        plugin:
            type: Tsp
            solver: 2opt

    visit_objects_pddl:
        plugin:
            type: Pddl
            domain_name: GotoObjectDomain
