/**:
  ros__parameters:
    submap_num_segments: 40
    submap_overlapping_segments: 20
    lc_required_associations: 8
    ego_id: 0
    ego_name: spot
    ego_flu_ref_frame: spot/body
    ego_odom_frame: spot/vision
    team_ids: [-1]
    team_names: ['']
    team_flu_ref_frames: ['']
    team_odom_frames: ['']
    prior_session_maps: ['/home/swarm/adt4_output/0507_b45/roman_map.pkl']
    prior_session_ids: [-1]