/**:
  ros__parameters:
    odom_frame: map
    body_frame: spot/body
    spot_ip: 10.0.0.3
    bosdyn_client_username: $(env ADT4_BOSDYN_USERNAME)
    bosdyn_client_password: $(env ADT4_BOSDYN_PASSWORD)
    use_fake_spot_interface: true
    use_fake_spot_pose: false
    fake_spot_external_pose: true
    fake_spot_static_pose: false
    fake_spot_x: 0.01
    fake_spot_y: 0.01
    fake_spot_z: 0.01
    fake_spot_yaw: 0.01
    follower_lookahead: 2.1
    semantic_model_path: path_to_semantic_model
    labelspace_path: labelspace_path
    labelspace_grouping_path: grouping_path
