/**:
  ros__parameters:
    heracles_ip: $(env ADT4_HERACLES_IP)
    heracles_port: $(env ADT4_HERACLES_PORT)
    map_frame: map
    robot_names: [euclid, hamilton, apollo, hilbert]
    publish_rate: 1.0
