_definitions:
  min_range: 0.4
  max_range: 5
map_frame: map
odom_frame: spot/odom
robot_frame: spot/body
enable_zmq_interface: false
publish_backend_tf: true
map_window:
  type: spatial
  max_radius_m: 8
robot_id: 0
input:
  type: RosInput
  inputs:
    frontleft:
      receiver:
        type: ClosedSetImageReceiver
        queue_size: 30
      sensor:
        type: camera_info
        min_range: 0.4
        max_range: 5
        extrinsics:
          type: ros
    frontright:
      receiver:
        type: ClosedSetImageReceiver
        queue_size: 30
      sensor:
        type: camera_info
        min_range: 0.4
        max_range: 5
        extrinsics:
          type: ros
active_window:
  volumetric_map:
    voxels_per_side: 16
    voxel_size: 0.1
    truncation_distance: 0.3
  tsdf:
    semantic_integrator:
      type: MLESemanticIntegrator
frontend:
  type: GraphBuilder
  pgmo:
    time_horizon: 15
    d_graph_resolution: 2.5
    mesh_resolution: 0.005
  objects:
    min_cluster_size: 40
    cluster_tolerance: 0.25
    bounding_box_type: RAABB
  surface_places:
    type: place_2d
    prefix: P
    pure_final_place_size: 3
    enable_place_purity: false
    impure_final_place_size: 1
    cluster_tolerance: 0.3
    min_cluster_size: 50
    max_cluster_size: 100000
    min_final_place_points: 10
    place_max_neighbor_z_diff: 0.5
    place_overlap_threshold: 0
backend:
  type: BackendModule
  serialize_dsg_mesh: false
  min_dsg_separation_s: 1
  publish_mesh: true
  min_mesh_separation_s: 10
  add_places_to_deformation_graph: false
  optimize_on_lc: true
  update_functors:
    agents:
      type: UpdateAgentsFunctor
    objects:
      type: UpdateObjectsFunctor
    surface_places:
      type: Update2dPlacesFunctor
      min_size: 3
  pgmo:
    run_mode: FULL
    embed_trajectory_delta_t: 5
    num_interp_pts: 3
    interp_horizon: 10
    add_initial_prior: true
    optimizer:
      type: KimeraRpgoOptimizer
      solver: LM
      gnc:
        inlier_probability: 0.9
        mu_step: 1.6
        max_iterations: 100
    covariance:
      odom: 0.01
      loop_close: 0.05
      sg_loop_close: 0.1
      prior: 0.01
      mesh_mesh: 0.01
      pose_mesh: 0.01
      place_mesh: 0.01
      place_edge: 10
      place_merge: 10
      object_merge: 10
