world_frame: map
robots:
- type: UnitInterface
  robot_id: 0
  robot_name: prior
  inputs:
    dgraph:
      type: FileDGraphInput
      dgrf_path: !env ADT4_PRIOR_DGRF_PATH
    dsg:
      type: FileDsgInput
      dsg_json: !env ADT4_PRIOR_DSG_PATH
- type: RosUnitInterface
  robot_id: 1
  robot_name: spot
  robot_frame: spot/vision
  inputs:
    dgraph:
      type: RosDGraphInput
    dsg:
      type: RosDsgInput
backend:
  type: MultiBackendModule
  add_places_to_deformation_graph: false
  add_objects_to_deformation_graph: false
  optimize_on_lc: true
  enable_node_merging: true
  update_functors:
    agents:
      type: UpdateAgentsFunctor
    objects:
      type: UpdateObjectsFunctor
    surface_places:
      type: Update2dPlacesFunctor
      min_size: 3
  initial_align:
    type: LoopClosureInitialAlign
    alignment_gnc_alpha: 0.7
    rot_sigma: 0.1
    trans_sigma: 10
  pgmo:
    run_mode: FULL
    embed_trajectory_delta_t: 5
    num_interp_pts: 3
    interp_horizon: 10
    optimizer:
      type: KimeraRpgoOptimizer
      solver: LM
      gnc:
        inlier_probability: 0.9
        mu_step: 1.6
        max_iterations: 100
    covariance:
      odom: 0.01
      loop_close: 0.05
      sg_loop_close: 0.1
      prior: 0.01
      mesh_mesh: 0.01
      pose_mesh: 0.01
      place_mesh: 0.01
      place_edge: 10
      place_merge: 10
      object_merge: 10
