---
world_frame: map
robots:
  # NOTE(Yun): for now due to needing to call env variables, robot_id 0 corresponding to file input interface is defined in launch file
  - type: RosUnitInterface
    robot_id: 1
    robot_name: $<env ADT4_ROBOT_NAME>
    robot_frame: $<env ADT4_ROBOT_NAME>/odom
    inputs:
      dgraph:
        type: RosDGraphInput
      dsg:
        type: RosDsgInput
backend:
  type: MultiBackendModule
  add_places_to_deformation_graph: false
  add_objects_to_deformation_graph: false
  optimize_on_lc: true
  enable_node_merging: true
  update_functors:
    agents: {type: UpdateAgentsFunctor}
    objects: {type: UpdateObjectsFunctor}
    surface_places: {type: Update2dPlacesFunctor, min_size: 3}
  initial_align:
    type: LoopClosureInitialAlign
    alignment_gnc_alpha: 0.9
    rot_sigma: 0.1
    trans_sigma: 10.0
  pgmo:
    run_mode: FULL  # kimera_pgmo run mode FULL is required
    embed_trajectory_delta_t: 5.0
    num_interp_pts: 3
    interp_horizon: 10.0
    optimizer:
      type: KimeraRpgoOptimizer
      solver: LM
      gnc: {inlier_probability: 0.7, mu_step: 1.6, max_iterations: 100}
    covariance:
      odom: 1.0e-04
      loop_close: 1.0e-01
      sg_loop_close: 1.0e-01
      prior: 1.0e-02
      mesh_mesh: 1.0e-02
      pose_mesh: 1.0e-02
      place_mesh: 1.0e-02
      place_edge: 10.0
      place_merge: 10.0
      object_merge: 10.0
