---
name: Lint-Awesome-DCIST-T4
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches:
      - main
      - develop

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        run: sudo apt-get update && sudo apt install pipx
      - name: Lint
        run: pipx install pre-commit && cd ${{github.workspace}} && pre-commit run --all-files
