/**:
  ros__parameters:
    occupancy_frame: $(var robot_name)/map
    odom_frame: $(var robot_name)/odom
    body_frame: $(var robot_name)/body
    spot_ip: $(env ADT4_BOSDYN_IP)
    bosdyn_client_username: $(env ADT4_BOSDYN_USERNAME)
    bosdyn_client_password: $(env ADT4_BOSDYN_PASSWORD)
    use_mid_level_planner: true
    use_fake_occupancy_map: false
    publish_fake_path_plan: true
    use_fake_spot_interface: true
    use_fake_spot_pose: false
    fake_spot_external_pose: true
    fake_spot_static_pose: false
    fake_spot_x: 0.01
    fake_spot_y: 0.01
    fake_spot_z: 0.01
    fake_spot_yaw: 0.01
    follower_lookahead: 2.1
    goal_tolerance: 2.8
    semantic_model_path: path_to_semantic_model
    labelspace_path: labelspace_path
    labelspace_grouping_path: grouping_path
    detector_model_path: $(env ADT4_WS)/weights/yolov8s-world.pt
